name: CI emscripten

on:
  push

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run build
        run: |
          chsh -s /bin/bash $USER
          echo $SHELL
          make -f Makefile.emscripten install-emsdk build-core