name: CI emscripten

on:
  push

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run build
        shell: bash
        run: |
          make -f Makefile.emscripten install-emsdk build-core