name: CI emscripten

on:
  push

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run build
        run: |
          sudo apt update -y && sudo apt install make -y
          ./easy-compile-ubuntu